### PR TITLE
[Fixes #14] Fixed ArrayObject totalPages()

### LINKED ISSUE #14: PHP Fatal error:  Unsupported operand types in ArrayObject.php on line 43
Hi
I'm getting this fatal error when I'm accessing `totalPages()` of `Photo` collection returned by `User->photos()`

### PR DESCRIPTION
**Pull request by freezy-sk**
Items of `$this->headers` are arrays so there I fixed it.

### CODE REVIEW

**Comment by dechuck** [comment]
Good catch!

Can you fixe the test in `test/ArrayObjectTest.php#testTotalPage` and be sure all tests are valid. The header mock up in it is wrong.

Let me know if you have issues running the tests.

**Comment by freezy-sk** [comment]
@dechuck I copied `.env.example` to `.env` and tried to run tests but in basic setup they are throwing too many errors. Does they need some specific setup?

**Comment by dechuck** [comment]
Actually, I need to update `.env.example` to reflect the VCR cassette variables.
You can use those variable in your .env

```
ACCESS_TOKEN=582c5d7ebe28bd707751a43c8e22dc5c0a4ba0a60dbe69d520677f47b7cfcc1b
API_HOST=api.unsplash.com
API_SCHEME=https
SITE_URI=https://unsplash.com
```

**Comment by freezy-sk** [comment]
@dechuck Thanks. It finally works with this configuration.

**Comment by dechuck** [comment]
Good the hear! I should merge it tomorrow morning.

Thanks a lot for this fix.

**Pull request merged**
