### PR TITLE
Fix documentation grammar.

### PR DESCRIPTION
**Pull request by aaronklaassen**
@lukechesser Could probably use one more pass.

### CODE REVIEW

**Comment by dechuck** [comment]
Thanks a lot! :smile:

**Comment by lukechesser** [comment]
@dechuck you want to merge this? I'll do a second pass after it's merged.

**Comment by lukechesser** [comment]
@dechuck can you merge this and update the wiki with the changes?

**Comment by dechuck** [comment]
Yeah! Going to do this.
I'll validate why the tests fail first. Should be done before the end of the afternoon.

**Comment by lukechesser** [comment]
Cool, just tag me when it's merged and I'll take a look through again for grammar etc.

Actually, hold off on updating the wiki until I do that.

**Pull request merged**
