### PR TITLE
Random photo endpoint

### PR DESCRIPTION
**Pull request by DannyWeeks**
I have implemented the random photo endpoint as mentioned in issue #17. I have added tests and also manually tested the endpoint in an app.

I'd just like to clarify if `featured=true` is the correct way of requesting featured images in the query string? I'm not exactly sure how to check if the image I was getting back was featured but assumed because the downloads were high!

If there are any changes you want made just let me know, I'm happy to help!

### CODE REVIEW

**Comment by dechuck** [comment]
Hi @DannyWeeks,
Thanks a lot for your contribution.

For the `featured=true`, you're right. It's the good way to retrieve the featured image.

I think it could be interesting to pass an array to the 'random', instead of multiple parameters. I think it will be a lot easier to only pass specific parameters to the method.

So, to retrieve a random photo of coffee we could do `Photo.random([‘query’ => ‘coffee’)` instead of `Photo.random(null,null,'', ‘coffee')`.

What do you think?

Everything else looks perfect. :smile:

Thanks again!

**Comment by DannyWeeks** [comment]
Yeah, using an array is a much more intuitive way of filtering the random photos! I will make the necessary changes now.

In my manual testing I seem to always be given the photo with the id of `71cd1rWqO8M` when requesting a featured image, any ideas why this might be happening?

**Comment by aaronklaassen** [comment]
@DannyWeeks Yeah that looks like an API bug. I'll get a fix in place.

**Comment by DannyWeeks** [comment]
Hey @dechuck I've updated to use the array, I wasn't 100% sure how to explain it in the [readme](https://github.com/DannyWeeks/Unsplash-PHP/tree/random-photo-endpoint#photo). Let me know what you think! :)

**Comment by dechuck** [comment]
Hey @DannyWeeks, 

Everything looks good to me. I will merge it into master and update the tag.
Again, thanks a lot for your contribution, it's really appreciated.

**Comment by DannyWeeks** [comment]
No worries @dechuck, glad I could help!

**Pull request merged**
